# This file was generated by GoReleaser. DO NOT EDIT.
class Mmake < Formula
  desc "Go wrapper for mmake, a make wrapper"
  homepage "https://github.com/tj/mmake"
  version "1.4.0"

  if OS.mac?
    url "https://github.com/tj/mmake/releases/download/v1.4.0/mmake_1.4.0_darwin_x86_64.tar.gz"
    sha256 "2dd3f00e340efa087657510032a8620991849290e38cd09b4d2aca5571753077"
  elsif OS.linux?
    url "https://github.com/tj/mmake/releases/download/v1.4.0/mmake_1.4.0_linux_x86_64.tar.gz"
    sha256 "65c0ef76bf05bd82f89b4a5908a12671774dd5f43a2f5d9ea3f53140a6772d77"
  end

  def install
    bin.install "mmake"
  end

  test do
    system "#{bin}/mmake help"
  end
end
